# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "archlinux/archlinux"

  config.vm.provider "virtualbox" do |v|
    v.gui = true
  end
  config.vm.synced_folder "../..", "/vagrant", mount_options: ["ro"]

  config.vm.provision "shell", inline: <<-SHELL
    pacman -Syyu --noconfirm git rsync
  SHELL
end
