#!/bin/sh

set -eu

case "${env}" in
    ubuntu) ;;
    *) exit
esac

version="$(curl -fsSL https://deb.nodesource.com/setup_current.x | sed -n 's/^NODEREPO="\(.*\)"$/\1/p')"
codename="$(lsb_release --codename --short)"

curl -fsSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo gpg --no-default-keyring --keyring /usr/share/keyrings/nodesource.gpg --import -
echo "deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/${version} ${codename} main" | sudo tee /etc/apt/sources.list.d/nodesource.list >/dev/null
echo "deb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/${version} ${codename} main" | sudo tee -a /etc/apt/sources.list.d/nodesource.list >/dev/null
