#!/bin/sh

set -eu

case "${env}" in
    ubuntu) ;;
    *) exit
esac

curl -fsSL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo gpg --no-default-keyring --keyring /usr/share/keyrings/yarnpkg.gpg --import -
echo "deb [signed-by=/usr/share/keyrings/yarnpkg.gpg] https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list >/dev/null
