# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/hirsute64"

  config.vm.provider "virtualbox" do |v|
    v.gui = !ENV['GUI'].to_s.empty?
  end
  config.vm.synced_folder "../..", "/vagrant", mount_options: ["ro"]

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get upgrade --assume-yes
  SHELL
end
